# Generated by Django 5.2.4 on 2025-08-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
