# Generated by Django 5.2.4 on 2025-08-04 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='note',
            new_name='message',
        ),
    ]
